databases:
  - name: construction-chat-db
    databaseName: construction_chat
    user: chat_user
    plan: free

services:
  - type: web
    name: construction-chat-app
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build && npm run setup
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: construction-chat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: PORT
        value: 10000